### ISSUE TITLE
Beware of min-width and min-height

### ISSUE THREAD

**Issue by raphaelgoetter** [Heydon/fukol-grids#18]
Hello,

You might consider adding some min-content fix on flex-items : 

```css
.fukol-grids > * {
  min-width: 0;
  min-height: 0;
}
```

Sources : 
- https://css-tricks.com/flexbox-truncated-text/
- http://www.alsacreations.com/astuce/lire/1701-images-responsive-flexbox-bug-ratio.html (fr)
