### ISSUE TITLE
In a percentage based fukol grid the margin in calc() should be double

### ISSUE THREAD

**Issue by nickrttn** [Heydon/fukol-grids#19]
Instead of this:
```css
.fukol-grid > *:first-child {
  flex-basis: calc(100% - 1em);
}
```

It should be this:
```css
.fukol-grid > *:first-child {
  flex-basis: calc(100% - 2em);
}
```

to account for the margin on both the left and the right side.

**Comment by nickrttn** [comment]
Instead of this:
```css
.fukol-grid > *:first-child {
  flex-basis: calc(100% - 1em);
}
```

It should be this:
```css
.fukol-grid > *:first-child {
  flex-basis: calc(100% - 2em);
}
```

to account for the margin on both the left and the right side.
