### ISSUE TITLE
100% width child

### ISSUE THREAD

**Issue by proweb** [Heydon/fukol-grids#9]
You write 

> Sometimes you want certain items to be narrower or wider. You can target these using `:nth-child`

So what I'm doing wrong? [http://codepen.io/proweb/pen/yaPRmX](http://codepen.io/proweb/pen/yaPRmX)

Why first child don't have right margin?

**Comment by Heydon** [comment]
@proweb Well spotted. I've changed the README and demo. You have to use calc to compensate for the gutter:

``` css
.fukol-grid > *:first-child {
  flex-basis: calc(100% - 1em);
}
```
